### ISSUE TITLE
Lost Buttons By name and Position

### ISSUE THREAD

**Issue by Artibug** [bitfocus/companion-module-thelightingcontroller#11]
So in the middle of setting up a lightshow for an event in 3 weeks, the presets for Buttons by Name and Position literally disappeared while I was working. I am running companion 3.2.2 and showexpress 9.3.8. Is this a change or a bug?

**Comment by thargy** [comment]
Hi @Artibug,

This module hasn't been updated in 3 years, as I no longer use QuickDMX myself. You'll see I left an issue (#7) when they first announced the migration path to port the module from version 2 of Companion to version 3. I have never done that work as there hasn't been enough interest, there would be significant challenges in creating a new development environment and effectively rewriting the whole module, and I have been busy on other projects. As such, I'm pleasantly surprised it works on version 3 at all!

Version 2 of companion had lots of idiosyncracies that I had to work around to make the module reliable, many of those were addressed in version 3, but it would not surprise me if my workarounds now clash in rare circumstances - which is probably what happened to you. Sadly though, it's been four years since I last looked seriously at the project, so your best hope is to fork it and submit a pull request, or see if anyone else is interested in doing the work.

Sorry, I couldn't be of more help.

**Comment by Artibug** [comment]
Actually it's all good. Mainly user error on my part. Somehow the control
with external app option had been unchecked. Once rechecked it was fine.
You can disregard the issue. Thank you for your help no matter what. It is
appreciated!!! Have Blessed day.

Patrick Hardy
Videographer/AV Professional
Quietly Making Noise Productions, LLC
***@***.***
www.qmnproductions.com
770.490.6203
