### ISSUE TITLE
Live buttons couple to Bitfocus Companion

### ISSUE THREAD

**Issue by Steffielight** [bitfocus/companion-module-thelightingcontroller#13]
Hi!  I was trying today some things to learn more about this program. Can somebody tell me how it do this:

How to connect a live button from quick dmx lighting software to stream deck xl Bitfocus Companion?

![livemodus](https://github.com/bitfocus/companion-module-thelightingcontroller/assets/165475805/1ecb0923-6be0-4ab9-a4e1-f44b4e200dc4)
![software](https://github.com/bitfocus/companion-module-thelightingcontroller/assets/165475805/a0f926ce-fb57-462c-94e3-f5d420fa2f63)

**Comment by thargy** [comment]
This is not the appropriate place to ask questions about using Companion; I encourage you to contact their Slack and forums. However, regarding this module -

## Step 1
Please read the [Readme](..) _fully_ and follow _all_ the instructions. You must correctly set up TLC & Companion as per the instructions.

## Step 2
Click on a button on the surface (your second image), then click on the 'Presets' tab (to the right of the image you copy-pasted); you will see buttons for all the addons that provide Presets. Click on the 'thelightingcontroller.com,...' button.

## Step 3
Choose the type of button you want to add. There are buttons by name and buttons by position, the first stay in sync based on the button's name in TLC, the second stay in sync based on the buttons position in TLC.  It is usually safer to use 'by name' if you don't change button names but move them around in TLC - for example, `rood`; otherwise, 'by position', in which case the button will always be mapped to a particular page and position in TLC (e.g. button 1 on first page). The button's name, colour, activation, etc., will stay in sync with whatever button has that name or that position, depending on which you select.

## Step 4
Drag the button from the preset to where you want it.  It will now stay in sync (Name, colour, etc.) with the TLC button.
